var MSG = {
  title: "PITSCO SEEKER",
  blocks: "Blocks",
  linkTooltip: "Save and link to blocks.",
  runTooltip: "Run the program defined by the blocks in the workspace.",
  badCode: "Program error:\n%1",
  timeout: "Maximum execution iterations exceeded.",
  trashTooltip: "Discard all blocks",
  openBlocksTooltip: "Open Blockly Program",
  saveBlocksTooltip: "Save Blockly Program",
  terminalTooltip: "Toggle REPL Serial Terminal",
  uploadBlocksTooltip: "Upload Code using USB",
  connectBlocksTooltip: "Connect to Robot",
  resetBlocksTooltip: "Reset | Restart",
  connectBTTooltip: "Connect to Robot over Bluetooth",
  connectUSBTooltip: "Connect to Robot over USB",
  uploadBTTooltip: "Send code to robot over Bluetooth",
  uploadUSBTooltip: "Send code to robot over USB",
  btNameTooltip: "Change robot's Bluetooth name",

  catLogic: "Logic",
  catLoops: "Loops",
  catMath: "Math",
  catText: "Text",
  catLists: "Lists",
  catColour: "Colour",
  catVariables: "Variables",
  catFunctions: "Functions",
  listVariable: "list",
  textVariable: "text",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this public link. We\'ll delete them if not used for a year. They are not associated with your account and handled as per Google\'s Privacy Policy. Please be sure not to include any private information.\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  loadError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  parseError: "Error parsing %1:\n%2\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the %1."
};
